name: SkyBlock
main: just.skyblock.SkyBlock
version: 0.1.0
description: Skyblock plugin
author: PureGero
api-version: 1.13
commands:
  skyblock:
    description: Skyblock commands
    aliases: [sky,sb,s,is,island]
  spawn:
    description: Go to spawn
  money:
    description: Money
    aliases: [mymoney,balance,bal,coins]
  pay:
    description: Give money to another player
    aliases: [givemoney]
  rank:
    description: Show your rank
    aliases: [myrank]
  ranks:
    description: List the ranks
    aliases: [ranklist]
  objectives:
    description: Objectives list
    aliases: [objective, obj, progress, achievements, achievement]
  slimechunk:
    description: Tells you were your slime chunk is
    aliases: [whereismyslimechunk, findmyslimechunk]
permissions:
  skyblock:
    default: true
  skyblock.admin:
    default: op